VIA_ENABLE = yes
LTO_ENABLE = yes
NKRO_ENABLE = yes
# NO_USB_STARTUP_CHECK = no
DYNAMIC_MACRO_ENABLE = yes
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no
MIDI_ENABLE = no
RGB_MATRIX_CUSTOM_USER = yes

SRC += led.c
